twilio/twilio-csharp

- src/Twilio.Api/AvailablePhoneNumbers.Async.cs
> Add missing callback param to overload invocation

- .travis.yml
- Twilio.nuspec
- src/Twilio.Api.Tests.Integration/CallTests.cs
- src/Twilio.Api/Calls.cs
- Add an overload to ListCall that allows you to pass a `to` number.
- Add Integration test
> Add overload to List Calls

- README.md
- src/Twilio.Api.WindowsPhone/Twilio.Api.WindowsPhone.csproj
- src/Twilio.Api.WindowsPhone/packages.config
- src/Twilio.Mvc/Twilio.Mvc.csproj
- src/Twilio.TaskRouter.Tests/TaskQueueTests.cs
- src/Twilio.TaskRouter.Tests/TaskTests.cs
- src/Twilio.TaskRouter.Tests/Twilio.TaskRouter.Tests.csproj
- src/Twilio.TaskRouter.Tests/WorkspaceTests.cs
- src/Twilio.TaskRouter.Tests/packages.config
- src/Twilio.TaskRouter/Twilio.TaskRouter.csproj
- src/Twilio.TaskRouter/packages.config
- src/Twilio.Trunking.Tests/Twilio.Trunking.Tests.csproj
- src/Twilio.Trunking.Tests/packages.config
- src/Twilio.Trunking/Twilio.Trunking.csproj
- src/Twilio.Trunking/packages.config
- src/packages/repositories.config
Hey, just adding some Ci integration and fixing some of the broken unit tests
> Add Ci and fix unit tests

- src/Twilio.Api/Core.cs
> Add TwilioRestClient overload for API Version and Base URL

- src/Twilio.IpMessaging/Members.Async.cs
- src/Twilio.IpMessaging/Members.cs
> Fix Update Member by setting RoleSid as required parameter

- src/Twilio.Auth/Twilio.Auth.csproj
- src/Twilio.Auth/packages.config
- src/Twilio.Conversations.Tests/Twilio.Conversations.Tests.csproj
- src/Twilio.Conversations.Tests/packages.config
- src/Twilio.IpMessaging/Core.cs
- src/Twilio.IpMessaging/Services.cs
- src/packages/repositories.config
- Fixed a couple of dependency version mismatch issues
- Also changed how IPM Service updates work.
> Edge release minor fixes

- src/Twilio.Api.Tests.Integration/Credentials.cs
- src/Twilio.IpMessaging.Tests/ChannelTests.cs
- src/Twilio.IpMessaging.Tests/Model/ChannelTests.cs
- src/Twilio.IpMessaging.Tests/Twilio.IpMessaging.Tests.csproj
- src/Twilio.IpMessaging/Channels.cs
- src/Twilio.IpMessaging/Model/Channel.cs
> Add unique name as an optional parameter for Channel creation. 

- Twilio.nuspec
- Twilio/JWT/AccessToken.cs
- Twilio/JWT/ConversationsGrant.cs
- Twilio/JWT/HttpUtility.cs
- Twilio/JWT/IGrant.cs
- Twilio/JWT/IpMessagingGrant.cs
- Twilio/JWT/Policy.cs
- Twilio/JWT/ScopeURI.cs
- Twilio/JWT/TaskRouterCapability.cs
- Twilio/JWT/TwilioCapability.cs
- Twilio/Twilio.csproj
- Twilio/packages.config
- Twilio35/Twilio35.csproj
- Twilio35/packages.config
Adds JWT and capability tokens back to CSharp.
> Add Twilio.JWT

- Twilio.Mvc.nuspec
* 3.2.2 - Remove unneeded dependency on Twilio package
- Update version of Twilio.TwiML dependency
> Twilio.Mvc: Remove unneeded dependency on Twilio package

- Twilio/Converters/StringEnumConverter.cs
> Handle null string enum values

- build.ps1
Also catches any PowerShell errors and fails the build.
> Fix build script to work with VS 2017 RTM

- src/Twilio/TwiML/Gather.cs
- test/Twilio.Test/TwiML/GatherTest.cs
This is a fix for #379 where some parameters for gather are missing. more information on the original ticket.
I've also added test cases for all the parameters.
> Add missing Gather attributes. Fixes #379

- .travis.yml
Appveyor currently tests against all supported versions
Unclear what travis tests against.
> Test against all supported versions on travis

- UPGRADE.md
This reverts commit 617c501b50fc3013d5560c311aca79178726f112.
> Revert "Revert "Document Sync breaking change in 5.9.x (#398)""

- src/Twilio/TwiML/TwiML.cs
VCORE-3651 Add support for *for* attribute in twiml element
> VCORE-3651 Add support for *for* attribute in twiml element

- src/Twilio/Http/SystemNetHttpClient.cs
- test/Twilio.Test/Http/SystemNetHttpClientTest.cs
> Add a comment and test to verify thread safety of async HTTP requests

- src/Twilio/Converters/StringEnumConverter.cs
- test/Twilio.Test/Converters/StringEnumConverterTest.cs
> Handle 'null' string enum lists during JSON deserialization

- src/Twilio/Types/Client.cs
- test/Twilio.Test/Types/ClientTest.cs
Relates to https://github.com/twilio/twilio-csharp/pull/456
> Perform case-insensitive check for 'client:' prefix

- src/Twilio/Types/SubscribeRule.cs
- src/Twilio/Types/SubscribeRulesUpdate.cs
> Add SubscribeRule and SubscribeRulesUpdate

- src/Twilio/Types/IceServer.cs
> Add urls property in ice servers

- README.md
> Fixed point and project highlight in README

- appveyor.yml
> Auto-deploy via Appveyor upon tagged commit to master

- src/Twilio/Clients/TwilioRestClient.cs
- src/Twilio/Exceptions/ApiException.cs
- src/Twilio/Exceptions/RestException.cs
- test/Twilio.Test/Clients/TwilioRestClientTest.cs
Add a new property named details to ApiException and RestException. Details is returned by selective apis to populate extra information about errors.
The Studio V2 flow api will be returning extra details with flow validation errors.
> feat: add details to api exception

- TROUBLESHOOTING.md
> docs: add troubleshooting guide

- .travis.yml
This reverts commit d662783913a34c3d2bee20a26470f48596cb25da.
Fixes #556 
> fix: Revert "Remove deploy to nuget"

- .github/workflows/test-and-deploy.yml
- Makefile
Adds SonarCloud integration to the test and deploy Github action workflow.
> feat: Add SonarCloud analysis

- .github/workflows/test-and-deploy.yml
> chore: prevent Sonarcloud from running on forks

- .github/workflows/test-and-deploy.yml
- Makefile
- test/Twilio.Test/ClusterTest.cs
Adds cluster test to the 6.0.0-rc branch.
> test: Cluster test for csharp

- .gitignore
open api generates hidden files: ".openapi-generator" and ".openapi-generator-ignore". Ignoring these files on commit.
> chore: ignore openapi autogenerated hidden files

- src/Twilio/Properties/AssemblyInfo.cs
Changed AssemblyInfomation version to pre-release RC version
> fix: corrected AssemblyInfomation release version

- src/Twilio/Rest/FlexApi/V1/GoodDataOptions.cs
- src/Twilio/Rest/FlexApi/V1/GoodDataResource.cs
Renaming GoodDatum to GoodData in current version to keep in sync with nuget package.
> fix: renamed resource and option file from GoodDatum to GoodData

- src/Twilio/Rest/Api/V2010/Account/Call/NotificationOptions.cs
- src/Twilio/Rest/Api/V2010/Account/Call/RecordingOptions.cs
- src/Twilio/Rest/Api/V2010/Account/CallOptions.cs
- src/Twilio/Rest/Api/V2010/Account/Conference/RecordingOptions.cs
- src/Twilio/Rest/Api/V2010/Account/ConferenceOptions.cs
- src/Twilio/Rest/Api/V2010/Account/Message/MediaOptions.cs
- src/Twilio/Rest/Api/V2010/Account/MessageOptions.cs
- src/Twilio/Rest/Api/V2010/Account/NotificationOptions.cs
- src/Twilio/Rest/Api/V2010/Account/RecordingOptions.cs
- src/Twilio/Rest/Numbers/V2/RegulatoryCompliance/BundleOptions.cs
Include a fix for https://github.com/twilio/twilio-oai-generator/pull/394
fixed header params in getparams method with postfix before and after in parameter name.
> fix: fixed header params with postfix before and after in name

- .github/workflows/test-and-deploy.yml
the test and deploy script is failing due to the bug in 7.0.400 dot net version. 
more info here https://github.com/actions/setup-dotnet/issues/383
> fix: Update dotnet version

- .github/workflows/test-and-deploy.yml
- src/Twilio/Converters/CustomConverters.cs
> chore: added custom converters for nested objects (#688)

- src/Twilio/Constant/EnumConstants.cs
> fix: removed unused constructor

- src/Twilio/Twilio.csproj
- test/Twilio.Test/Twilio.Test.csproj
> chore: Upgrade net6

- .github/workflows/test-and-deploy.yml
Sonarcloud requires Java17 for running. Added Java17 setup in the test workflow.
> chore: setup java17 in test workflow

- .github/workflows/test-and-deploy.yml
> chore: added code signing workflow

- .github/workflows/test-and-deploy.yml
> chore: corrected nuget push command

- .github/workflows/test-and-deploy.yml
> chore: corrected repo name in code-signing workflow

- src/Twilio/Twilio.csproj
> chore: add VersionSuffix to csproj file

- .github/workflows/test-and-deploy.yml
> chore: skipping duplicate nuget push

- src/Twilio/Http/SystemNetHttpClient.cs
- src/Twilio/Twilio.csproj
Adding back support for net35, net462, netstandard2.1
> fix: adding support for net35 net462 and netstandard2.1

- src/Twilio/Twilio.csproj
Bumped the version of System.IdentityModel.Tokens.Jwt library to 6.34.0 to fix the security vulnerability https://github.com/advisories/GHSA-59j7-ghrg-fj52
> fix: updating jwt version

- src/Twilio/Twilio.csproj
Adds README.md to Nuget. Referred [this](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/)
> docs: adding readme to nuget

- Makefile
- src/Twilio/JWT/AccessToken/TaskRouterGrant.cs
- test/Twilio.Test/Jwt/AccessToken/AccessTokenTest.cs
- test/Twilio.Test/Twilio.Test.csproj
As per Taskrouter version 2, it now uses grant-based token. Adding support for that. Similar to https://github.com/twilio/twilio-node/pull/222
> fix: Adding TaskRouterGrant file

- src/Twilio/Rest/Domain.cs
> fix: Update Domain.cs to remove orgs api entry

- test/Twilio.Test/ClusterTest.cs
> feat : Modfiying cluster tests for public OAuth in C#

- README.md
- examples/BearerTokenAuthentication.md
- test/Twilio.Test/ClusterTest.cs
> feat: Updating documents and examples for Public OAuth feature uptake

- src/Twilio/Base/IOptions.cs
Converting pageSize to long since larger values are expected
> chore: convert pageSize from int to long

- src/Twilio/Http/HttpMethod.cs
> chore: added patch method support

- examples/BearerTokenAuthentication.md
- src/Twilio/Http/BearerToken/ApiTokenManager.cs
- src/Twilio/Http/BearerToken/OrgsTokenManager.cs
updating token endpoint to iam domain
> chore: updating token endpoint to iam domain

- examples/PublicOAuthAuthentication.md
> docs: update oauth example
