src/Twilio.TaskRouter.Tests/ActivityTests.cs
src/Twilio.TaskRouter/Activities.Async.cs
src/Twilio.TaskRouter/Activities.cs

This field on an Activity cannot be updated with the REST API, so removing this from the helper library.

Remove Update Activity available boolean

---

src/Twilio.TaskRouter.Tests/CapabilityTests.cs
src/Twilio.TaskRouter/Capability/TaskRouterCapability.cs

- Allow fetching Reservations under a Worker by default
- Allow updating Reservations under a Worker

Loading Reservations under a Worker by default in TaskRouter JS SDK

---

src/Twilio/Http/SystemNetHttpClient.cs

So when calling the non-asynchronous methods in the library, we do a Task.Wait() on the asynchronous versions. Those will deadlock in an MVC or WPF app because it will try to resume on the same thread to maintain the same context, but we've already blocked the thread with Task.Wait().
Adding `.ConfigureAwait(false)` within the library code tells our library we don't need it to return with the same context and thus avoids the deadlock.
See here for reference: https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

Fix async/await for MVC/WPF apps

---

src/Twilio/TwiML/Gather.cs
src/Twilio/TwiML/VoiceResponse.cs
test/Twilio.Test/TwiML/VoiceResponseTest.cs

It is not currently possible to set the `finishOnKey` attribute on `Gather` to the empty string. This PR enables this scenario.

Allow empty string for gather finishOnKey attribute

---

src/Twilio/JWT/AccessToken/Token.cs
src/Twilio/JWT/Client/EventStreamScope.cs
src/Twilio/JWT/Client/IncomingClientScope.cs
src/Twilio/JWT/Client/OutgoingClientScope.cs
src/Twilio/JWT/Taskrouter/PolicyUtils.cs

Refactored string concatenation within the jwt namespace to remove usage references to the C# 6.0 string interpolation feature.

Remove "$" String Interpolation to Support Compilation in .NET <4.6

---

src/Twilio/JWT/AccessToken/VoiceGrant.cs
test/Twilio.Test/Jwt/AccessToken/AccessTokenTest.cs

https://issues.corp.twilio.com/browse/CLIENT-4492
To support JS Clients per this spec:
https://paper.dropbox.com/doc/Proposal-FPA-Token-Format-for-Programmable-Voice-SDKs-xhdFHD6N3aPW9GRp4dXNX

Add incoming.allow to AccessToken VoiceGrant

---

src/Twilio/TwiML/TwiML.cs
test/Twilio.Test/TwiML/FaxResponseTest.cs
test/Twilio.Test/TwiML/MessagingResponseTest.cs
test/Twilio.Test/TwiML/VoiceResponseTest.cs

- Allow generic name for TwiML nodes
- Add tests for `MessagingResponse`, `VoiceResponse` and `FaxResponse`
Note: tests are auto-generated; will make a separate PR for the code generation.

Allow adding TwiML children with generic tag names

---

src/Twilio/Security/RequestValidator.cs
test/Twilio.Test/Security/RequestValidatorTest.cs

Adds two public methods: you can manually validate request body yourself, or you can pass in the request body to the Validator to validate based on the `bodySHA256` parameter.

Add a method for validating request body

---

src/Twilio/Clients/TwilioRestClient.cs
src/Twilio/Exceptions/CertificateValidationException.cs
src/Twilio/Twilio.cs
test/Twilio.Test/Clients/TwilioRestClientTest.cs

This adds a method at the top level TwilioClient that passes the request down to TwilioRestClient (which is where all the pipes were in place to make this happen).

Add helper method for testing if new SSL cert can be consumed

---

src/Twilio/Security/RequestValidator.cs
test/Twilio.Test/Security/RequestValidatorTest.cs
test/Twilio.Test/Twilio.Test.csproj

Previously, we (I) assumed that we'd be passing in both parameters and request body. This is impossible, because parameters would _be_ the post body. This makes the logic either/or.

POST doesn't receive params and body for body validation

---

src/Twilio/Twilio.csproj

Since these three Twilio dependencies require Newtonsoft.Json 10.0.1, we should require it as well:
```
<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.2" />
<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="5.1.2" />
<PackageReference Include="Microsoft.IdentityModel.Logging" Version="1.1.2" />
```
The hope is that this eliminates the need for binding redirects in a simple application that only has Twilio as a dependency.
See issue #431

Bump Newtonsoft.Json to 10.0.1 to try to fix #431

---

src/Twilio/Security/RequestValidator.cs
test/Twilio.Test/Security/RequestValidatorTest.cs

Our internal system sends the bodySHA256 parameter as hex, not base64, so this PR fixes that.

Switch body validator to use hex instead of base64

---

Doxyfile
Doxyheader.html

Adding Twilio's Google Tag Manager configuration so that usage analytics can be collected for the autogenerated docs.

Add Google Tag Manager to generated docs (will add google analytics)

---

src/Twilio/Http/SystemNetHttpClient.cs

We've had a long investigation process of getting wrong responses in https://www.twilio.com/console/support/tickets/1767573 . I still don't know why we haven't had such issues earlier, but it's the usage of shared field LastResponse that causes getting wrong responses. I have tested it locally.
Please merge this ASAP and we will update Twilio library on our Production environment.
Best regards,
Yury Semerikov
ServiceTitan Telecom Developer Team Lead

SystemNetHttpClient.MakeRequestAsync is thread safe

---

src/Twilio/Rest/Api/V2010/Account/CallOptions.cs
src/Twilio/Rest/Api/V2010/Account/CallResource.cs

Closes https://github.com/twilio/twilio-csharp/issues/402

Update the call create 'from' param to be endpoint type for client identifier support

---

src/Twilio/Security/RequestValidator.cs
test/Twilio.Test/Security/RequestValidatorTest.cs

add validation for urls with non-standard ports

---

README.md

Cleans up the docs a bit. Removes old "update" and clarifies .NET version support.

Docs cleanup, clarify .NET support

---

src/Twilio/Types/SubscribeRule.cs

Before GA of the Bandwidth Profile API, we have decided to change the TrackPriority to `STANDARD` as this more accurately describes the priority we're using.

VIDEO-2338 TrackPriority.STANDARD

---

src/Twilio/Http/Net35/WebRequestClient.cs
src/Twilio/Http/Net35/WebRequestWrappers.cs
src/Twilio/Http/Response.cs
src/Twilio/Http/SystemNetHttpClient.cs

The default HTTP client stores 'Last Request' and 'Last Response' information for access to more data about the raw API request/response. The response object did not contain the headers until now.

feat: include API response headers in 'Last Response'

---

src/Twilio/Twilio.csproj

On Visual Studio the current icon for `twilio-csharp` appears to be scrambled. 
This change modifies the `.ico` file with `.png`.
Note: I wasn't entirely sure how to test this given that this is hosted with NuGet, but perhaps there is additional functionality that can be utilized for testing.
- [] I have added tests that prove my fix is effective or that my feature works

fix: Change Default Logo from .ico to .png in NuGet

---

.travis.yml
src/Twilio/Twilio.csproj
test/Twilio.Test/Twilio.Test.csproj

Allows for building .NET Framework libraries on Linux without requiring Mono.
References:
https://medium.com/@dmaman/travis-ci-setup-for-multi-framework-solution-in-c-be32315c79d1
https://andrewlock.net/using-reference-assemblies-to-build-net-framework-libararies-on-linux-without-mono/
Fixes https://github.com/twilio/twilio-csharp/issues/536

fix: use ReferenceAssemblies NuGet packages

---

src/Twilio/Clients/TwilioRestClient.cs
test/Twilio.Test/Clients/TwilioRestClientTest.cs

This PR removes behavior disparity between TwilioRestClient's Request and RequestAsync methods in terms of propagating Edge and Region properties to the request, effectively fixing RequestAsync's support for edge servers.
Fixes #565

fix: Propagate Edge and Region properties from client to request when making async request

---

src/Twilio/JWT/BaseJwt.cs
src/Twilio/Twilio.csproj

Patching newer versions of JwtHeader including "cty".
There is an overloaded constructor that could take the header directly and sort it out there.
However, it is not available in the old System.IdentityModel.Tokens.Jwt, 5.1.2.
This seems like an easy way to deal with it and be able to upgrade beyond 6.17.0.
* Existing test cover this.

fix: Patching newer versions of JwtHeader including "cty"

---

Dockerfile
README.md

Enables docker to be used to build and test the code.
* Tests passes using the instruction in the readme.
* No code modifled.

test: Modified Dockerfile to be able to easily build and test.

---

.github/workflows/test-and-deploy.yml
Makefile

DII-640
Make sonar exclusions a variable to reuse this file and run with different coverage areas

fix: Make sonar exclusions a variable to reuse this file

---

src/Twilio/Converters/PhoneNumberConverter.cs

Resolved [Issue](https://github.com/twilio/twilio-csharp/issues/539) as part of this PR. 
Serialization was failing when 'from' parameter was null, so added a check to handle the null values.
Solution is referenced from [here](https://github.com/SignalR/SignalR/commit/389427e88eaff56bd9e40bcf7521af4d1c603f07)

fix: handling null 'from' parameter 

---

src/Twilio/Converters/PhoneNumberConverter.cs

Resolved https://github.com/twilio/twilio-csharp/issues/539 as part of this PR.
Serialization was failing when 'from' parameter was null, so added a check to handle the null values.

fix: handle missing "from" parameter exception

---

.github/workflows/test-and-deploy.yml

Adding timestamper url for nuget package signing. Upload to nuget repository is failing because timestamper url is not provided. Timestamper url from the provider of the code signing certificate is added as timestamp argument

fix: Adding timestamper url for nuget package signing

---

.github/workflows/test-and-deploy.yml
src/Twilio/Converters/CustomConverters.cs

Created custom converters for List of custom models and  models.

chore: added custom converters for nested objects

---

src/Twilio/Base/IOptions.cs
src/Twilio/Http/Request.cs
src/Twilio/Properties/AssemblyInfo.cs
src/Twilio/Twilio.csproj

- Changed the csharp version to 7.0.0-rc.0
- Modified the Request constructor to set contentType and request body

chore: Updated csharp rc version and changed Request constructor

---

.github/workflows/test-and-deploy.yml

This is a hotfix: pinning sonarscanner version to 5.x.x (compatible version)
Sonarscanner has done some major upgrades in their latest release [v6.0.0](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/6.0.0.81631), which is causing the sonar cli to [fail](https://github.com/twilio/twilio-csharp/actions/runs/7449236497/job/20265424247#step:6:106) in all build steps. 

fix: pin sonarscanner version

---

.github/workflows/test-and-deploy.yml

chore: added code-signing-workflow

---

README.md
examples/BearerTokenAuthentication.md
examples/PublicOAuthAuthentication.md

feat: Adding example for using public OAuth

---

test/Twilio.Test/ClusterTest.cs

Adding test cases for public oauth uptake in C#

feat: Adding test cases for public oauth uptake

---

.github/workflows/test-and-deploy.yml
src/Twilio/Clients/TwilioRestClient.cs
src/Twilio/Twilio.cs

https://twilio-engineering.atlassian.net/browse/DII-1756
Adding overloaded method in TwilioRestClient with and without authstrategy. 
Restoring the existing method in TwilioRestClient and adding a new overloaded method with a new mandatory parameter authStrategy

fix: Update TwilioRestClient.cs to add overloaded method in rest client
